import { Helmet } from "react-helmet";

function Terms()
{
    return (
        <>
            <Helmet>
                <title>Terms and Conditions of Sale - Dawn Scientific</title>
                <meta
                    name="description"
                    content="“Agreement” means these Terms and Conditions of Sale. "
                />
            </Helmet>
            <section className="page-title">
                <div className="container">
                    <div className="title-wrapper">
                        <div className="title">
                            <h1>Terms and Conditions of Sale</h1>
                        </div>
                    </div>
                </div>
            </section>

            <section className="policy-wrapper">
                <div className="container">
                    <div className="row">
                        <div className="col-md-10">
                            <div className="widget">   
                                <ol>
                                    <li><strong>Definitions.</strong>
                                        <ol type="a">
                                            <li>“<strong>Agreement</strong>” means these Terms and Conditions of Sale.&nbsp;</li>
                                            <li>“<strong>Confidential Information</strong>” means all non-public proprietary and/or confidential information including, but not limited to, manufacturing sources of products (including the manufacturer name, manufacturer site, origin information, and other source information (including as disclosed through survey requests); facility, equipment, or service suppliers; design, procurement, security, qualification, maintenance, and supply chain information; findings from audits of DAWN SCIENTIFIC, INC’s suppliers; Product or Services specifications, drawings, or prototypes; standard operating policies, procedures, and training; pricing; computer network and software systems or other technology information; business and or marketing plans; financial data; customer contact information (and other customer material or data); non-public intellectual property; and organization or personnel information.</li>
                                            <li>“<strong>Customer</strong>” means any person or entity purchasing Products or Services from DAWN SCIENTIFIC, INC, either directly or through its employees or other individuals.&nbsp;</li>
                                            <li>“<strong>Products</strong>” means the goods that DAWN SCIENTIFIC, INC provides to Customer and is comprised of Manufactured Products and Sourced Products:
                                                <ol type="i">
                                                    <li>“<strong>Manufactured Products</strong>” means:
                                                        <ol type="1">
                                                            <li>“<strong>Custom Products</strong>” means those products that are assembled (i.e., with respect to clinical laboratory or science education materials kits) or manufactured by DAWN SCIENTIFIC, INC to the written specifications (e.g., relating to the components, raw materials, stability, manufacture, testing, storage, handling, labeling, packaging, and/or shipping of the product) provided by Customer and agreed upon by DAWN SCIENTIFIC, INC; and</li>
                                                            <li>“<strong>Self-Manufactured Products</strong>” means those products manufactured by certain of DAWN SCIENTIFIC, INC International, LLC’s subsidiaries and affiliated entities, excluding Custom Products.&nbsp;</li>
                                                        </ol>
                                                    </li>
                                                    <li>“<strong>Sourced Products</strong>” means:
                                                        <ol type="1">
                                                            <li>“<strong>Core Products</strong>” means those products from third-party suppliers with whom DAWN SCIENTIFIC, INC has an established supply chain agreement generally covering delivery terms, warranty, pricing, and stocking.&nbsp; These products are generally available on DAWN SCIENTIFIC, INC’s websites or in DAWN SCIENTIFIC, INC catalogs, and may include customer-specific products and spot-buys from customers of Core Products within a given product line that are therefore subject to the established supply chain agreement with the supplier of Core Products as referenced above; and</li>
                                                            <li>“<strong>MarketSource Products</strong>” (also referred to as “Third-Party Products”) means those products from third-party suppliers that are not Core Products or products not covered under the established supply chain agreements referenced in the definition of Core Products.&nbsp; MarketSource Products may be designated as MarketSource on DAWN SCIENTIFIC, INC’s website, viewable online only by a specific customer, or be in the form of a spot-buy or purchase through DAWN SCIENTIFIC, INC’s “Click to Source” or “Open Requisition” program.</li>
                                                        </ol>
                                                    </li>
                                                </ol>
                                            </li>
                                            <li>“<strong>Services</strong>” means work performed by employees or subcontractors of DAWN SCIENTIFIC, INC for Customer in accordance with a Scope of Work or similar order instrument that details the work and fees associated with a services engagement (each, an “SOW”).&nbsp; DAWN SCIENTIFIC, INC’s Services offerings may include, but are not limited to: equipment and instrument services, scientific services, laboratory and production support, procurement, vendor managed inventory, kit assembly and ancillary supply site distribution services, and supply chain management.</li>
                                            <li>“<strong>Taxes</strong>” means any and all applicable taxes, duties, fees, levies, or other assessments imposed or collected by any governmental entity worldwide or any political subdivision thereof, however designated or levied, on sales of Products or Services, or sales, use, transfer, goods, and services or value added tax or any other duties or fees related to any Customer payment made to DAWN SCIENTIFIC, INC for DAWN SCIENTIFIC, INC’s provision of Products and/or Services to Customer under or pursuant to this Agreement; exclusive, however, of any taxes imposed upon the net income or capital of DAWN SCIENTIFIC, INC, any taxes in lieu of such net income taxes, and any other taxes that are to be borne by DAWN SCIENTIFIC, INC under applicable law.</li>
                                            <li>“<strong>DAWN SCIENTIFIC, INC</strong>” means DAWN SCIENTIFIC, INC International, LLC, and its divisions, subsidiaries, and affiliated entities utilizing these Terms and Conditions of Sale on their websites, quotation forms, and/or invoices.</li>
                                        </ol>
                                    </li>
                                    <li><strong>Agreement Terms; Acceptance by Customer.</strong>&nbsp; DAWN SCIENTIFIC, INC RESERVES THE RIGHT TO ACCEPT OR REJECT ANY ORDER, TO TERMINATE THIS AGREEMENT, OR TO CHANGE THESE TERMS AND CONDITIONS OF SALE, WITHOUT NOTICE TO CUSTOMER, AT ANY TIME FOR ANY REASON, AND RECEIPT BY CUSTOMER OF A DAWN SCIENTIFIC, INC QUOTATION, PRICE LIST, OR CATALOG DOES NOT CONSTITUTE AN OFFER TO SELL. ALL SALES BY DAWN SCIENTIFIC, INC ARE SUBJECT TO THE TERMS AND CONDITIONS OF THIS AGREEMENT, AND EXPRESSLY CONDITIONED UPON CUSTOMER’S ASSENT THERETO. &nbsp;CUSTOMER WILL BE DEEMED TO HAVE ACCEPTED THESE TERMS AND CONDITIONS BY ISSUING A PURCHASE ORDER OR BY ANY OTHER STATEMENT (INCLUDING, WITHOUT LIMITATION, VIA E-MAIL), ACT, COURSE OF CONDUCT, DEALING, OR PERFORMANCE CONSTITUTING ACCEPTANCE UNDER APPLICABLE LAW, INCLUDING, WITHOUT LIMITATION, FAILURE TO OBJECT IN WRITING TO THESE TERMS AND CONDITIONS WITHIN A REASONABLE TIME OR BY ACCEPTANCE OF AND/OR PAYMENT FOR THE PRODUCTS OR SERVICES.&nbsp; ALL PURCHASE ORDERS OR SIMILAR ORDER INSTRUMENTS ISSUED BY CUSTOMER WILL BE GOVERNED ONLY BY THE TERMS AND CONDITIONS OF THIS AGREEMENT, AND ANY ADDITIONAL AND/OR INCONSISTENT TERMS AND CONDITIONS SET FORTH IN ANY ACKNOWLEDGMENT, PURCHASE ORDER, OR ACCEPTANCE DOCUMENTS REQUESTED FROM AND/OR PROVIDED BY CUSTOMER ARE EXPRESSLY REJECTED. &nbsp;NEITHER DAWN SCIENTIFIC, INC’S DELIVERY OF THE PRODUCTS NOR PROVISION OF THE SERVICES NOR ANY OTHER ACTION, CONDUCT, OR PERFORMANCE SHALL CONSTITUTE ACCEPTANCE OF TERMS OR CONDITIONS DIFFERENT FROM THE TERMS AND CONDITIONS OF THIS AGREEMENT.&nbsp;</li>
                                    <li><strong>Delivery.</strong>&nbsp; Domestic delivery of all Products will be FCA Origin Dock (Incoterms 2010), and title and risk of loss in all Products will transfer to Customer upon DAWN SCIENTIFIC, INC’s delivery of such Products to the carrier or agent at DAWN SCIENTIFIC, INC’s or DAWN SCIENTIFIC, INC’s supplier’s facility, as applicable, regardless of the freight term specified for transportation purposes.&nbsp; Unless otherwise agreed to by DAWN SCIENTIFIC, INC in writing, DAWN SCIENTIFIC, INC reserves the right to choose the carrier, forwarding company, and means of transport. &nbsp;Where and to the extent permitted by applicable law, shipping and handling fees, special packaging materials, carrier surcharges (including, without limitation, fuel surcharges), shipping palettes, environment-controlled shipping, and/or hazardous material fees imposed by government regulation will be added separately to the invoice. &nbsp;Customer acknowledges that DAWN SCIENTIFIC, INC may refer to shipping and other fees on DAWN SCIENTIFIC, INC’s invoices as “freight,” “handling fees,” “expense recovery,” or similar terms.&nbsp; The shipping and other fees that DAWN SCIENTIFIC, INC charges may not be limited to DAWN SCIENTIFIC, INC’s actual transportation costs and may include other shipping and handling costs. &nbsp;<br />Shipping and/or delivery dates set forth in a DAWN SCIENTIFIC, INC quotation or order acknowledgement are based on estimates at the time of the quotation or order acknowledgement.&nbsp; DAWN SCIENTIFIC, INC shall use commercially reasonable efforts to ship the Products in accordance within the shipping and/or delivery dates, provided that the foregoing will not constitute a guaranty of compliance with the quoted shipping and/or delivery dates, and DAWN SCIENTIFIC, INC will not be liable for any direct or indirect costs or damages incurred by Customer or any third party, including, without limitation, incidental or consequential damages, resulting from late deliveries.&nbsp;</li>
                                    <li><strong>Damaged Shipments; Inspection.</strong> &nbsp;Customer shall immediately inspect all deliveries for shipping damage upon receipt. &nbsp;If any external damage is noticed, Customer shall accept the shipment only after the driver has noted the damage on both carrier’s and Customer’s copies of the delivery receipt and Customer has requested an inspection by the carrier. &nbsp;Customer shall keep all containers and packing material for inspection. &nbsp;Customer shall promptly inspect all shipments for concealed shipping damage, defects, or shortages, notify DAWN SCIENTIFIC, INC of any such damage, defect, or shortage, and cooperate with DAWN SCIENTIFIC, INC in arranging an inspection by the carrier and the filing of a freight claim as applicable; provided that on all sales where Customer arranges transportation, in the event of loss or damage in transit, Customer should file its own claim with the carrier.&nbsp; &nbsp;With respect to shipping damage, Customer must contact DAWN SCIENTIFIC, INC to request inspection within twenty-four (24) hours of delivery or unconditionally waive any right to make any claim relating to the damaged Products, including, without limitation, under the warranty set forth herein. &nbsp;With respect to other claims, Customer’s failure to notify DAWN SCIENTIFIC, INC within thirty (30) days of delivery (or Customer’s non-receipt the Products in the case of non-delivery) of defects or shortages reasonably discoverable upon proper inspection will be deemed an unconditional waiver of any right to make any claim relating to the defective or missing Products, including, without limitation, under the warranty set forth herein.</li>
                                    <li><strong>Export Shipment Terms.&nbsp; </strong>Unless otherwise agreed to by DAWN SCIENTIFIC, INC in writing, delivery of orders by DAWN SCIENTIFIC, INC exports will be EXW Origin Dock (Incoterms 2010).&nbsp; Customer will have fifteen (15) days to pick up the order after being notified by DAWN SCIENTIFIC, INC of freight availability at DAWN SCIENTIFIC, INC’s designated Named Place, after which DAWN SCIENTIFIC, INC reserves the right to assess and bill Customer for storage fees, including but not limited to demurrage.&nbsp; For routed exports, where Customer’s nominated freight forwarder is used, all claims for damage will be the responsibility of Customer.</li>
                                    <li><strong>Prices.</strong>
                                        <ol type="a">
                                            <li><strong>Products.&nbsp; </strong>Unless explicitly specified in a written price quotation, all prices and Product specifications are subject to change without prior notice to Customer.&nbsp; DAWN SCIENTIFIC, INC price quotations are valid for the period specified on the quotation; provided, however, that quoted pricing is subject to adjustment based on shipment arrangements or other terms and conditions which were not part of DAWN SCIENTIFIC, INC’s original price quotation.&nbsp; If DAWN SCIENTIFIC, INC has not provided a price quotation, pricing will be determined based on the Product price published on DAWN SCIENTIFIC, INC’s website at the time of the order.&nbsp; For orders for Manufactured Products placed prior to any annual price change with shipment occurring after such annual price change, DAWN SCIENTIFIC, INC reserves the right to change its price to Customer to the current Product price as of the date of shipment.</li>
                                            <li><strong>Fixed-Price Services.&nbsp; </strong>The price to Customer for fixed-price Services will be as set forth in the respective SOW.&nbsp;&nbsp; Unless otherwise expressly stated in each applicable SOW: (i) all Service fees are quoted on a monthly basis, and Customer shall pay such Service fees regardless of temporary planned or unplanned Customer site closures; (ii) all prices stated in the SOW will be subject to an annual review and increase, effective January 1 of each calendar year for the duration of the Services engagement; and (iii) overtime that is approved by Customer will be billed to Customer at the hourly overtime rate set forth in the applicable SOW.&nbsp; All monthly Services fees are due in full regardless of whether DAWN SCIENTIFIC, INC on-site employees or subcontractors were present at Customer’s site(s) each day (or each hour of each day) for the applicable month that is being invoiced, provided that the Services in any applicable SOW have otherwise been materially performed.&nbsp;&nbsp;&nbsp; Additional Services or change in scope in any applicable SOW(s) may require additional resources to meet the appropriate service level.&nbsp; In the event that additional resources are needed, the parties will review the applicable SOW and negotiate the scope of the Services performed and/or any Services cost increase. The fees and charges for any follow-on or additional work not described in the applicable SOW will be performed at DAWN SCIENTIFIC, INC’s then-current rates for such work.</li>
                                            <li><strong>Other Services.</strong>&nbsp; Prices for Services not covered under a fixed-price SOW will be those prices in effect at the time the Services are provided or quoted, and may be adjusted to include any necessary surcharge(s). &nbsp;Unless otherwise agreed by DAWN SCIENTIFIC, INC in writing, DAWN SCIENTIFIC, INC prices do not include the cost of any related inspections, inspection fees, or permits.&nbsp; Prices for billable parts will be DAWN SCIENTIFIC, INC’s standard rates in effect at the time of installation. &nbsp;Subject to the limited warranties specified herein, the sale of billable parts will be considered final. If equipment requires major repair outside the scope of any contract with Customer, DAWN SCIENTIFIC, INC will provide Customer with an itemized estimate of the cost to perform said repair.&nbsp; Installation terms for purchase orders for the installation of scientific laboratory equipment or furniture will be as set forth on DAWN SCIENTIFIC, INC’s quotation form.&nbsp;</li>
                                            <li><strong>Sales Tax.</strong>&nbsp; Taxes, where applicable, will be added as a separate line item to the invoice price.&nbsp; Customer shall pay to DAWN SCIENTIFIC, INC the amount of any Taxes. &nbsp;If any claim is made against DAWN SCIENTIFIC, INC for any such Taxes, DAWN SCIENTIFIC, INC shall promptly notify Customer of the amount of such Taxes and Customer shall promptly pay such amount to DAWN SCIENTIFIC, INC or its designated payee.&nbsp; If Customer possesses or otherwise enjoys tax-exempt status, Customer shall provide a duly authorized certificate of tax exemption to DAWN SCIENTIFIC, INC prior to or at the time of order placement or as otherwise requested by DAWN SCIENTIFIC, INC from time to time, and shall notify DAWN SCIENTIFIC, INC upon change in Customer’s tax-exempt status.&nbsp; Customer will be responsible for any Medical Device Excise Tax for IRS purposes for any Products that are medical devices purchased by Customer hereunder.</li>
                                        </ol>
                                    </li>
                                    <li><strong>Payment Terms.</strong> &nbsp;Customer shall pay individual invoices net thirty (30) days from date of invoice, unless other credit terms are agreed to in writing by DAWN SCIENTIFIC, INC; summary invoices, if any, will be due as agreed. &nbsp;Payments are to be made in the currency invoiced by DAWN SCIENTIFIC, INC. &nbsp;Customer shall provide DAWN SCIENTIFIC, INC, concurrent with each payment, with remittance information in sufficient detail (to the invoice level or line level, as applicable) to allow DAWN SCIENTIFIC, INC to properly apply payments or credit memos to outstanding receivable(s) on DAWN SCIENTIFIC, INC’s accounts receivable sub-ledger for Customer.&nbsp; Any payments received no later than 2.00 PM Eastern Time at DAWN SCIENTIFIC, INC’s lockbox will be credited to Customer’s account as of the date received, while payments received after 2.00 PM Eastern Time will be credited to Customer’s account the following business day. &nbsp;Payment in the form of a check will be credited once the deposit appears in DAWN SCIENTIFIC, INC’s bank account; no post-dated checks will be accepted.&nbsp; Delinquent accounts will be subject to a service charge on past due amounts of the lesser of between one and one-half percent (1.5%) and three percent (3%) per month, depending on region, or the maximum amount permitted by law, plus Taxes, reasonable attorneys’ fees, and other collections costs, if any, incurred by DAWN SCIENTIFIC, INC. &nbsp;DAWN SCIENTIFIC, INC recommends payments be made by wire transfer or ACH method to ensure timely receipt by DAWN SCIENTIFIC, INC. &nbsp;DAWN SCIENTIFIC, INC reserves the right to: (i) require C.O.D. (subject to a handling fee) or impose more stringent payment requirements (including, without limitation, payment in advance) on Customer if Customer’s account is overdue or if Customer has an unsatisfactory credit or payment record, as determined by DAWN SCIENTIFIC, INC in its sole discretion, and to refuse to sell to Customer or otherwise perform hereunder until all overdue amounts are paid in full; (ii) charge a convenience fee on any post-sale credit card payments by Customer; (iii) charge a fee for any checks rejected due to insufficient funds; (iv) charge a service fee for any re-invoicing requested by Customer; and (v) furnish payment history data and related information to third party companies for fraud protection and credit risk reduction.</li>
                                </ol>

                                <ol>
                                    <li><strong>Security Interest.</strong>&nbsp; If Customer fails to pay the total sum due hereunder within sixty (60) days of shipment, DAWN SCIENTIFIC, INC hereby reserves and Customer hereby grants a purchase money security interest in the Products sold hereunder and the proceeds thereof.&nbsp; In the event of default by Customer of any of its obligations to DAWN SCIENTIFIC, INC, DAWN SCIENTIFIC, INC shall have the right to repossess the Products sold hereunder without liability to Customer.&nbsp; Customer hereby authorizes DAWN SCIENTIFIC, INC to file one or more financing statements signed only by DAWN SCIENTIFIC, INC without Customer’s signature and to use a copy of this Agreement as an exhibit to any financing statement.&nbsp; Upon request of DAWN SCIENTIFIC, INC, Customer agrees to promptly execute financing statements and such other instruments as DAWN SCIENTIFIC, INC desires to perfect or maintain its security interest.</li>
                                    <li><strong>Cancellation and Product Return Policy.</strong> &nbsp;Except for Products that do not meet the limited Product warranty set forth herein, Customer may only cancel or return Products in accordance with the following:
                                        <ol type="a">
                                            <li>Customer may not cancel or modify an order without the prior written consent of DAWN SCIENTIFIC, INC, which may be withheld for any reason or no reason at all, and any changes may be subject to price adjustment and/or cancellation fees.&nbsp; Custom Products are not cancellable.&nbsp; In the event DAWN SCIENTIFIC, INC consents to the cancellation of Custom Products, Customer shall reimburse DAWN SCIENTIFIC, INC for any and all goods or services that were procured by DAWN SCIENTIFIC, INC for the Custom Products, any works-in-progress for Custom Products, and any charges incurred by DAWN SCIENTIFIC, INC for the receipt or return of goods used to build Custom Product(s).&nbsp; If any Services hereunder are canceled or terminated, Customer will pay to DAWN SCIENTIFIC, INC the reasonable costs and expenses incurred by DAWN SCIENTIFIC, INC prior to receipt of notice of such cancellation, plus DAWN SCIENTIFIC, INC’s usual rate of profit for similar work. The minimum cancellation charge for Services is fifteen percent (15%) of the total Services price.&nbsp;</li>
                                            <li>All Product returns must be authorized by DAWN SCIENTIFIC, INC, and DAWN SCIENTIFIC, INC reserves the right to reject any returns requested more than thirty (30) days after the delivery date. &nbsp;DAWN SCIENTIFIC, INC must receive all authorized returns within thrity (30) days of the return authorization.&nbsp; Custom Products are not returnable.&nbsp; DAWN SCIENTIFIC, INC reserves the right to reject any return shipment of Product that has not been authorized by DAWN SCIENTIFIC, INC or to return such shipment to Customer at Customer’s expense.&nbsp; If any&nbsp; Product is erroneously shipped to or returned to a DAWN SCIENTIFIC, INC facility, Customer will be responsible for removing the&nbsp; Product from DAWN SCIENTIFIC, INC’s facility immediately in accordance with applicable laws and regulations.&nbsp; All returns are subject to a minimum fifteen percent (15%) restocking charge for Sourced Products and a minimum twenty-five percent (25%) restocking charge for Manufactured Products. &nbsp;In the event DAWN SCIENTIFIC, INC authorizes a return of Manufactured Products, Customer will be responsible for all disposal fees in addition to any restocking charges. &nbsp;Customer is responsible for all transportation fees related to returned Product unless otherwise authorized in advance by DAWN SCIENTIFIC, INC. &nbsp;To ensure proper credit, each Product return must include the following information:
                                                <ol type="i">
                                                    <li>Customer Name and Address</li>
                                                    <li>Purchase Order Number</li>
                                                    <li>DAWN SCIENTIFIC, INC Shipping Order Number</li>
                                                    <li>Date of Invoice and Invoice Number</li>
                                                    <li>Item Number and Quantity of Returned Product(s)</li>
                                                    <li>DAWN SCIENTIFIC, INC Return Authorization Number</li>
                                                    <li>Reason for Return</li>
                                                </ol>
                                            </li>
                                            <li>Products not authorized for return include:
                                                <ol type="i">
                                                    <li>Products that have been provided under terms indicating that they are non-returnable</li>
                                                    <li>Products not in completely resalable condition (including, without limitation, open Products, sampled Products, or Products with damaged, missing, or defaced labeling or packaging)</li>
                                                    <li>Products in less than full-case quantities that were sold in full-case quantities</li>
                                                    <li>Chemicals, reagents, diagnostics, cultivation media, flammable material, sterile Products, or controlled Products</li>
                                                    <li>Laboratory apparatus or instruments that have been used or are without the original packaging, labeling, and manuals</li>
                                                    <li>Refrigerated Products, temperature controlled Products, live specimens, or other perishables</li>
                                                    <li>Products which are not inventoried by DAWN SCIENTIFIC, INC (“non-stocked Products”) and are not able to be returned to the manufacturer</li>
                                                    <li>Products purchased on a special-order basis (including, without limitation, non-standard furniture Products)</li>
                                                    <li>Products not purchased by Customer from DAWN SCIENTIFIC, INC</li>
                                                    <li>Products with an expired shelf life or an expiration date too short for resale</li>
                                                    <li>Discontinued Products</li>
                                                    <li>Custom Products</li>
                                                </ol>
                                            </li>
                                            <li>Where the return of hazardous material is authorized by DAWN SCIENTIFIC, INC, Customer shall pack and label each return shipment of hazardous materials in accordance with applicable laws and regulations applying to transportation of hazardous materials and provide shipping documents that comply with applicable laws and regulations. &nbsp;When necessary, Customer shall include with each return shipment of equipment a certification from an authorized representative of Customer that the equipment was properly decontaminated in accordance with applicable laws and regulations and recommended guidelines. &nbsp;Customer shall ship the Product to the service center indicated by DAWN SCIENTIFIC, INC with the transportation charges prepaid. &nbsp;To ensure prompt handling, Customer shall place the return authorization number on the outside of the package and utilize any return authorization provided by DAWN SCIENTIFIC, INC as a packing slip with the returned Products.&nbsp; All returned Products are subject to DAWN SCIENTIFIC, INC’s inspection and acceptance.&nbsp; Title and risk of loss in the returned Products will transfer to DAWN SCIENTIFIC, INC only upon DAWN SCIENTIFIC, INC’s acceptance of the Products.</li>
                                            <li>In the event a DAWN SCIENTIFIC, INC entity establishes a returns and/or cancellation policy that differs from the terms set forth in this Section 9, the stricter DAWN SCIENTIFIC, INC requirement shall prevail in the event of a conflict.&nbsp; &nbsp;&nbsp;</li>
                                        </ol>
                                    </li>
                                    <li><strong>Weights and Containers.&nbsp; </strong>
                                        <ol type="a">
                                            <li>DAWN SCIENTIFIC, INC’s weights and counts shall govern unless proved to be in manifest error.&nbsp;</li>
                                            <li>Unless covered by separate contract, returnable containers (each, a “Container”) are the property of DAWN SCIENTIFIC, INC and are leased to Customer.&nbsp; Payment of a deposit or rental fee, when required by DAWN SCIENTIFIC, INC, does not convey title to such Containers.&nbsp; Customer shall return each Container empty, as defined pursuant to U.S. Environmental Protection Agency regulation 40 CFR 261.7, within sixty (60) days from date of shipment, freight charges collect and in compliance with applicable laws and regulations, including but not limited to those of the U.S. Department of Transportation.&nbsp; Upon receipt of the Container within sixty (60) days, in good condition, any deposit will be returned or credited to Customer.&nbsp; Cost of Containers not returned to DAWN SCIENTIFIC, INC within the time specified shall be charged to Customer’s account. &nbsp;&nbsp;</li>
                                            <li>Customer is responsible for any damage, destruction, or misuse of the Containers caused by Customer, normal wear and tear excepted.&nbsp; Customer shall not use or permit the use of the Containers in a manner that will permit the introduction of any contamination or of any liquid, solid, or gas, except inert gas for propellant purposes (not including oxygen or compressed air), into the Containers.&nbsp; DAWN SCIENTIFIC, INC reserves the right to charge for loss of use of a Container as a result of Customer loss, damage, contamination, improper handling, or other action that prevents DAWN SCIENTIFIC, INC from using the Container in the normal course of business, including, without limitation, any Container repair and/or Container cleaning fees for any Containers that are damaged or contaminated but serviceable or that have opened tamper-evident seals, if applicable.&nbsp; Customer also agrees to pay to replace any Container which is lost or damaged beyond repair by Customer.&nbsp; Additional terms and conditions or policies, as posted on DAWN SCIENTIFIC, INC’s website or otherwise communicated to Customer from time-to-time, may apply to DAWN SCIENTIFIC, INC’s provision of Containers.</li>
                                        </ol>
                                    </li>
                                    <li><strong>Product and Services Warranties; Limitation of Liability.</strong>
                                        <ol type="a">
                                            <li><strong>Limited Product Warranty for Sourced Products.</strong>&nbsp; DAWN SCIENTIFIC, INC warrants to the original Customer only that all Core Products sold hereunder will conform to the manufacturer’s specifications and release tolerances for a term equal to the warranty period stated in the Product manufacturer’s literature.&nbsp; Notwithstanding the foregoing, any Core Products that are software and any software incorporated in or necessary to use the Core Products (“Software Products”) are warranted solely by the applicable manufacturer or licensor, and DAWN SCIENTIFIC, INC shall pass through, to the extent permitted, the manufacturer’s and/or licensor’s warranties.&nbsp; Customer’s use of any Software Product is subject to the terms and conditions of the manufacturer’s and/or licensor’s license terms, including any end user license agreement, in whatever form (e.g., terms packaged with the Software Products or “click-through” terms), in addition to this Agreement.&nbsp; For all MarketSource Products, DAWN SCIENTIFIC, INC shall use reasonable efforts to assist Customer in obtaining sellers’ and manufacturers’ warranties applicable to the Products sold to Customer hereunder, consistent with the warranties obtained from such sellers and manufacturers by DAWN SCIENTIFIC, INC.&nbsp;</li>
                                            <li><strong>Limited Product Warranty for Manufactured Products.</strong>&nbsp; DAWN SCIENTIFIC, INC warrants to the original Customer only that Self-Manufactured Products will materially conform to DAWN SCIENTIFIC, INC’s standard specifications in effect on the date of shipment for the shorter of ninety (90) days from the date of delivery or the shelf-life of the Self-Manufactured Product.&nbsp; For a period of ninety (90) days from the date of delivery, DAWN SCIENTIFIC, INC warrants to the original Customer only that Custom Products will be assembled or manufactured, as applicable, to the specifications provided by Customer and agreed upon by DAWN SCIENTIFIC, INC.&nbsp; The foregoing warranties are limited to Manufactured Products, as applicable, bearing DAWN SCIENTIFIC, INC’s label in DAWN SCIENTIFIC, INC’s original packaging.&nbsp; DAWN SCIENTIFIC, INC does not warrant as to the safety, efficacy, or performance of any such Custom Products or as to the quality of such Custom Products to the extent attributable to the specifications.&nbsp; With respect to Custom Products that are kits, the limited warranty for component Products is as set forth in Section 11(a).&nbsp; Custom Products are subject to a plus or minus (+/-) ten percent (10%) yield policy with regard to volume produced.</li>
                                            <li><strong>Services Warranty.</strong>&nbsp; DAWN SCIENTIFIC, INC warrants that Services provided hereunder will be of the kind and quality designated and will be performed by qualified personnel.&nbsp; DAWN SCIENTIFIC, INC shall use reasonable efforts, based on the information supplied by Customer, to have all Services performed in a workmanlike and professional manner by employees or subcontractors of DAWN SCIENTIFIC, INC having a level of skill commensurate with the requirements of this Agreement.&nbsp; DAWN SCIENTIFIC, INC’s performance of the Services called for by this Agreement do not and will not violate any applicable law, rule, or regulation; any contracts with third parties; or any third-party rights in any patent, trademark, copyright, trade secret, or similar right.&nbsp; The following warranty periods will apply to the Services: (i) thirty (30) days after the work is completed for Services performed under an existing Services engagement; (ii) forty-eight (48) hours for any Services not performed under an existing Services engagement (a “call service”); or (iii) one (1) year from the installation date on installation Services for laboratory casework.&nbsp; All parts provided by DAWN SCIENTIFIC, INC in performing the Services will meet the manufacturer’s specifications for a term equal to the warranty period stated in the part manufacturer’s literature.</li>
                                            <li><strong>Exclusions.</strong>&nbsp; Customer must notify DAWN SCIENTIFIC, INC of defective or non-conforming Products within the warranty periods specified in the limited Product warranty set forth herein or within thirty (30) days after Customer learns of the facts giving rise to the claim, whichever first occurs, and Customer’s failure to give notice of any claim within the applicable time period shall be deemed an absolute and unconditional waiver of such claim.&nbsp; The liability of DAWN SCIENTIFIC, INC under the limited Product warranty set forth herein will not extend to any Products that are abused, altered, improperly stored, or misused by Customer or any other persons or entities or that become defective or non-conforming through the actions or inaction of Customer or any other persons or entities, including through the combination with other chemicals or products.&nbsp; Customer will have the obligation of substantiating the chain of custody of the Products following delivery of the Products to Customer.&nbsp; DAWN SCIENTIFIC, INC is not responsible for the impact of factors including, without limitation, machine cycles, sanitation, humidity, and operator practices (including, without limitation, misuse, abuse, and/or negligent operation, or unauthorized modifications, adjustments, and/or repairs) on serviced equipment and will not be required to perform Services or provide the warranty set forth herein on equipment subjected to such factors. &nbsp;Any Services performed by DAWN SCIENTIFIC, INC on equipment subjected to such factors will be on a time and materials basis only.&nbsp; All formulae, drawings, illustrations, descriptive matter, and particulars contained in DAWN SCIENTIFIC, INC’s catalogs, website, and marketing materials, and any technical advice or other statements given by DAWN SCIENTIFIC, INC or its representatives with respect to the use of the Products or any results that may be obtained therefrom, are indicative only and do not form a part of this Agreement and are not representations and warranties of any kind.&nbsp;</li>
                                            <li><strong>Disclaimer.</strong>&nbsp; DAWN SCIENTIFIC, INC HEREBY DISCLAIMS ALL OTHER WARRANTIES, CONDITIONS, OR GUARANTEES WITH RESPECT TO THE SUBJECT MATTER OF THIS AGREEMENT, WHETHER STATUTORY, WRITTEN, ORAL, EXPRESS, OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY (i) WARRANTY OF MERCHANTABILITY, NON-INFRINGEMENT, SUITABILITY, SUSTAINABILITY, OR FITNESS FOR A PARTICULAR PURPOSE; (ii) WARRANTY ARISING FROM COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE;&nbsp; AND (iii) ANY IMPLIED OR EXPRESS WARRANTY OF CONFORMITY TO MODELS OR SAMPLES OF MATERIALS.</li>
                                            <li><strong>Product Remedy.</strong>&nbsp; At DAWN SCIENTIFIC, INC’s request, Customer shall promptly forward to DAWN SCIENTIFIC, INC any allegedly defective or non-conforming Product or a representative sample thereof, as specified by DAWN SCIENTIFIC, INC.&nbsp; If any Product warranted hereunder proves defective or non-conforming, as determined by DAWN SCIENTIFIC, INC in its sole reasonable discretion, DAWN SCIENTIFIC, INC’s sole and exclusive obligation and Customer’s sole and exclusive remedy hereunder will be for DAWN SCIENTIFIC, INC, at DAWN SCIENTIFIC, INC’s option, to: (i) replace at no cost to Customer, any such defective or non-conforming Product with a non-defective or conforming Product; (ii) in the event a return is authorized, credit Customer’s account for all amounts paid with respect to the defective or non-conforming Product upon DAWN SCIENTIFIC, INC’s receipt of, and opportunity to evaluate, the defective or non-conforming Product; or (iii) repair or have repaired (including, through re-working or re-processing, as applicable) a defective or non-conforming Product. In the event of replacement, the replacement Product will be warranted for the remainder of the original warranty period.&nbsp; For purposes of this Agreement, a defective or non-conforming Product is defined only as a Product that does not meet the limited product warranty set forth herein, and excludes Products that fail to meet any fitness of use by Customer or any unique Customer operating conditions or applications.</li>
                                            <li><strong>Services Remedy.</strong>&nbsp; With respect to the labor, if any Services warranted hereunder prove defective or non-conforming, DAWN SCIENTIFIC, INC’s sole liability and Customer’s sole remedy hereunder will be for DAWN SCIENTIFIC, INC, at DAWN SCIENTIFIC, INC’s option to: (i) re-perform the Services, at no cost to Customer; or (ii) credit Customer’s account for all amounts paid with respect to the defective or non-conforming Services.&nbsp; With respect to any parts provided by DAWN SCIENTIFIC, INC in performing the Services, if any such parts prove defective or non-conforming during the first thirty (30) days after installation, DAWN SCIENTIFIC, INC’s sole liability and Customer’s sole remedy hereunder will be for DAWN SCIENTIFIC, INC, at DAWN SCIENTIFIC, INC’s option, to: (i) refund the purchase price; or (ii) modify, repair, or supply a replacement part, including labor and travel, free of charge to Customer.&nbsp; For the remainder of the warranty period, DAWN SCIENTIFIC, INC’s sole liability and Customer’s sole remedy hereunder will be for DAWN SCIENTIFIC, INC, at DAWN SCIENTIFIC, INC’s option, to: (i) refund the purchase price; or (ii) modify, repair, or supply a replacement part, provided Customer agrees to pay reasonable labor, travel time, and expenses to and from a service location authorized by DAWN SCIENTIFIC, INC. &nbsp;DAWN SCIENTIFIC, INC, at its option, may require Customer to return the part to DAWN SCIENTIFIC, INC, F.O.B. origin, or may modify, repair, or supply a replacement part at the point of installation. &nbsp;DAWN SCIENTIFIC, INC will accept no responsibility if such part has been improperly operated or maintained, or if Customer has permitted any unauthorized or third-party modifications, adjustments, and/or repairs to the part.</li>
                                            <li><strong>Waiver.</strong>&nbsp; Customer acknowledges that DAWN SCIENTIFIC, INC is not the manufacturer of any of the Sourced Products sold hereunder.&nbsp; Customer hereby waives any and all actions, claims, suits, and demands of any type whatsoever (including, without limitation, claims based on strict liability, products liability, tort, or contract) against DAWN SCIENTIFIC, INC, its subcontractors, or its agents, or any of its or their respective employees, for personal injury, wrongful death, or property damage arising out of or in any way connected with the Services or Customer’s receipt, handling, storage, possession, transportation, disposal, purchase, resale, or use of the Products (whether used singly or in combination with other products), except to the extent caused by the gross negligence of DAWN SCIENTIFIC, INC, its subcontractors, or its agents, or any of its or their respective employees.&nbsp; Notwithstanding any other provision of this Agreement, DAWN SCIENTIFIC, INC disclaims, and Customer releases DAWN SCIENTIFIC, INC from, any and all liability for claims based upon the death or bodily injury to any person or for the loss of, damage to, or destruction of any property so long as DAWN SCIENTIFIC, INC, its subcontractors, or its agents were acting in compliance with Customer policies, procedures, and specifications of which DAWN SCIENTIFIC, INC had been given notice</li>
                                            <li><strong>Limitation of Liability.</strong>&nbsp; IN NO EVENT WILL DAWN SCIENTIFIC, INC HAVE ANY OBLIGATION OR LIABILITY FOR ANY EXEMPLARY, PUNITIVE, INCIDENTAL, INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, LOSS OF PROFITS, REVENUE, BUSINESS, USE, DATA, PRODUCTIVITY, OR GOODWILL OR COST OF CAPITAL, RECALL, OR COVER) WHETHER BASED ON CONTRACT (INCLUDING, WITHOUT LIMITATION, WARRANTY), TORT (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER THEORY OR FORM OF ACTION, EVEN IF DAWN SCIENTIFIC, INC HAS BEEN ADVISED OF THE POSSIBILITY THEREOF. &nbsp;THE TOTAL LIABILITY OF DAWN SCIENTIFIC, INC (INCLUDING ITS SUBCONTRACTORS AND AGENTS), IF ANY, FOR DAMAGES RELATING TO THIS AGREEMENT OR ANY PRODUCT OR SERVICE WILL BE AN AMOUNT EQUAL TO THE PRICE OR FEES PAID FOR THE PARTICULAR PRODUCT(S) OR SERVICES IN RESPECT TO WHICH SUCH DAMAGES ARISE, IN NO EVENT TO EXCEED $1,000,000 UNITED STATES DOLLARS.&nbsp; HOWEVER, THESE PROVISIONS DO NOT LIMIT OUR LIABILITY THAT CANNOT BE LIMITED BY LAW.&nbsp;</li>
                                        </ol>
                                    </li>
                                    <li><strong>Indemnity.&nbsp; </strong>Customer shall indemnify, defend, and hold harmless each of DAWN SCIENTIFIC, INC, its subsidiaries, affiliated entities, and divisions, and its or their respective successors, assigns, officers, directors, shareholders, subcontractors, agents, employees, and representatives (each, a “Customer-Indemnified Party”) from and against, and in respect of, any and all actions, claims, suits, judgments, damages, liabilities, losses, settlement payments, penalties, costs, and expenses (including, without limitation, attorneys’ fees) of every kind whatsoever (collectively, “Damages”) arising out of, from, or in connection with any: (i) patent, copyright, or trademark infringement, or violation of any other proprietary right, arising out of the use of any Product or any specifications furnished by Customer; (ii) breach by Customer of any term or provision of this Agreement; (iii) Damages arising out of or relating to Customer’s receipt, handling, storage, possession, transportation, disposal, purchase, resale, or use of any Product (whether used singly or in combination with other products); and (iv) wrongful or negligent act or omission by any of Customer or its officers, directors, shareholders, agents, servants, employees, and representatives; provided, that this section will not obligate Customer to indemnify any Customer-Indemnified Party for any portion of Damages directly attributable to, and directly caused by, the negligence of a Customer-Indemnified Party.&nbsp; Customer may not settle any such claim against a Customer-Indemnified Party without the prior written consent of such Customer-Indemnified Party.&nbsp; If Customer elects not to assume such defense, the Customer-Indemnified Party may elect to do so and Customer shall pay all costs and expenses of counsel selected by such Customer-Indemnified Party in connection with such defense.&nbsp; Any legal counsel appointed by Customer to defend such a claim must be experienced in the type of litigation involved and must be reasonably satisfactory to the Customer-Indemnified Party.&nbsp; Customer and each Customer-Indemnified Party shall cooperate fully in connection with all matters related to the defense of any such claim.</li>
                                    <li><strong>Customer’s Obligations, Products.&nbsp; </strong>Customer represents and warrants that it is familiar with the characteristics, qualities and uses of the Products that it is purchasing from DAWN SCIENTIFIC, INC and acknowledges that there may be hazards associated with the possession and use of the Products.&nbsp; Customer is responsible for instructing and warning its employees and all other persons who may come into contact with the Products regarding such hazards.&nbsp; Unless otherwise expressly stated on the Products or in the documentation accompanying the Products, the Products are intended for research only and are not to be used for any other purpose, including, without limitation, unauthorized commercial uses, in vitro diagnostic uses, ex vivo or in vivo therapeutic uses, or any type of consumption by or application to humans or animals, and DAWN SCIENTIFIC, INC does not assume any warranty or liability for such uses unless stated on the Product or in the Product documentation.&nbsp; Customer is solely responsible for conducting all necessary testing and verification, including for fitness for the intended purpose, prior to the use of Product(s) purchased from DAWN SCIENTIFIC, INC.</li>
                                    <li><strong>Customer’s Obligations, Services.&nbsp; </strong>With respect to the Services, Customer shall at its expense: (i) make available to DAWN SCIENTIFIC, INC space and facilities, including, but not limited to, functional telephone and internet connectivity, reasonably satisfactory to DAWN SCIENTIFIC, INC and appropriate for the safe and efficient performance of the Services; (ii) for ongoing Services engagements, give DAWN SCIENTIFIC, INC sixty (60) days’ notice prior to any production down time that will last longer than seven (7) days; (iii) provide adequate access to all necessary customer systems, facilities, and facility-related training for DAWN SCIENTIFIC, INC on-site employees and subcontractors identified as providers of the Services; and (iv) ensure proper and adequate back-up and storage procedures for Customer’s data and records.</li>
                                    <li><strong>Export Controls.</strong>&nbsp; Products purchased or received under this Agreement, which may include technology and software, are subject to the customs and export control laws, restrictions, regulations, and orders of the United States of America (“U.S.”) and may also be subject to the customs and export laws and regulations of the country in which the Products are manufactured and/or received. &nbsp;Customer agrees to comply with all applicable export laws, rules, restrictions, and regulations of any relevant jurisdiction, including, without limitation, the Export Administration Act of 1979 and the Arms Export Control Act of 1976, and represents and warrants that it shall not: (i) export, or transfer for the purpose of re-export, any Product to any prohibited or embargoed country or to any denied, blocked, or designated person or entity in violation of applicable law; or (ii) transfer, by electronic transmission or otherwise, any software or technology to a foreign national or a foreign destination in violation of applicable law. &nbsp;Customer represents and warrants that it is not on the Denied Persons, Specially Designated Nationals, or Debarred Persons List, or any equivalent list maintained by a foreign regulatory authority, and is not otherwise prohibited by law from purchasing the Products or Services hereunder. &nbsp;Customer shall obtain any license to export, re-export or import as may be required.</li>
                                    <li><strong>Anti-corruption.</strong>&nbsp; Customer represents and warrants that: (i) it is familiar with and understands the terms of the U.S. Foreign Corrupt Practices Act of 1977&nbsp; (“U.S. FCPA”), and that it shall comply with the U.S. FCPA and all other applicable anti-bribery or anti-corruption laws or regulations of any other country or jurisdiction that are applicable to the parties’ business activities hereunder; (ii) no principal, partner, officer, director, or employee of Customer is or will become an official of any governmental body of any country or jurisdiction (other than the U.S.) that is applicable to the parties’ business activities hereunder; and (iii) it has not and shall not offer, pay, give, or promise to&nbsp; pay or give, directly or indirectly (including through a third party or intermediary) any payment or gift of any money or thing of value to any government official, government employee (or employee of any company owned in part by a government), political party, political party official, or candidate for any government or political office (each, a “Government Official”) to influence any acts or decisions of such Government Official or to induce such official to use his or her influence with the local government to effect or influence the decision of such government in order to assist either DAWN SCIENTIFIC, INC or Customer in its performance of their obligations under this Agreement or to benefit DAWN SCIENTIFIC, INC. &nbsp;Failure by Customer to comply with this section will be deemed a material breach of a material provision of this Agreement and DAWN SCIENTIFIC, INC will have the right to immediately terminate this Agreement and its performance without any liability to Customer.</li>
                                    <li><strong>Confidential Information.</strong> &nbsp;Customer shall maintain in confidence, not disclose to any third party, and not use, except for the specific purpose of performing under this Agreement, all Confidential Information furnished to it by DAWN SCIENTIFIC, INC in connection with this Agreement, as a result of discussions, negotiations, or other communications with DAWN SCIENTIFIC, INC in relation to the Products or Services, or derived from DAWN SCIENTIFIC, INC in performance of this Agreement, and shall return to DAWN SCIENTIFIC, INC, upon request, all copies then in Customer’s possession of DAWN SCIENTIFIC, INC’s Confidential Information. &nbsp;Customer shall inform its employees, agents, and representatives of these obligations and shall require them to assume equivalent obligations, and is liable for the acts and omissions of its employees, agents, and representatives with respect to DAWN SCIENTIFIC, INC’s Confidential Information.&nbsp; Customer acknowledges that DAWN SCIENTIFIC, INC would not have any adequate remedy at law for the breach by Customer of any one or more of its obligations contained in this section, and agrees that in the event of any such actual or potential breach, DAWN SCIENTIFIC, INC may, in addition to the other remedies that may be available, file a suit in equity to enjoin Customer therefrom.</li>
                                    <li><strong>Ownership Rights.&nbsp; </strong>Except as expressly set forth herein, no right, title or interest in or to DAWN SCIENTIFIC, INC’s intellectual property or proprietary rights (“Intellectual Property Rights”) is granted by DAWN SCIENTIFIC, INC to Customer whether by implication, estoppel, or otherwise, and the sale of Products and Services to Customer hereunder shall have no effect on DAWN SCIENTIFIC, INC’s Intellectual Property Rights with respect to the Products and Services, including, without limitation, any and all patent, trade secret, copyright, trademark, trade dress, and service mark rights relating to the Manufactured Products.&nbsp; Without limiting the foregoing, DAWN SCIENTIFIC, INC is and will remain the sole and exclusive owner of all right, title and interest in and to its standard operating procedures, specifications, drawings, and designs, and, if applicable, its proprietary software licensed to Customer hereunder, including any improvements or other inventions relating thereto.&nbsp; Customer agrees to respect all such rights, and to take or permit to be taken no actions which would infringe upon such rights.&nbsp; Customer shall not derive or attempt to derive by reverse engineering, disassembling, or otherwise any portion of the proprietary software.&nbsp; As between Customer and DAWN SCIENTIFIC, INC, all Intellectual Property Rights in and to the Services or any materials, processes, ideas, concepts, techniques, inventions, discoveries, or improvements produced by DAWN SCIENTIFIC, INC or provided by DAWN SCIENTIFIC, INC under this Agreement will be the property of DAWN SCIENTIFIC, INC.&nbsp; Effective upon completion of the Services and payment by Customer of the fees and expenses invoiced by DAWN SCIENTIFIC, INC with respect thereto, Customer will have a nonexclusive license to use the materials and processes developed and provided by DAWN SCIENTIFIC, INC under this Agreement for Customer throughout Customer’s organization.&nbsp; Customer’s interest in and obligations with respect to any programming, materials, or data to be obtained from third-party vendors, whether or not obtained with the assistance of DAWN SCIENTIFIC, INC, will be determined in accordance with the agreements and policies of such vendors.&nbsp;</li>
                                    <li><strong>Miscellaneous.</strong>
                                        <ol type="a">
                                            <li><strong>Force Majeure.</strong>&nbsp; DAWN SCIENTIFIC, INC will not be liable in the event it is prevented in whole or in material part from performing its obligations under this Agreement by circumstances beyond its reasonable control (including, without limitation, any war, riot, insurrection, terrorist act, civil commotion, labor strike, lockout, slowdown, or other civil disorder; fire, flood, storm, earthquake, natural disaster, or other act of God; shortages or inability to obtain necessary labor, power, fuel, energy, materials, supplies, equipment, machinery, or manufacturing facilities at reasonable prices from regular sources; machinery breakage; failure of a communications or Internet provider; transportation delays; or any then prevailing applicable law, rule, or regulation, including export or import controls, or other act or order of any court, government or governmental agency).</li>
                                            <li><strong>Nature of Relationship.</strong>&nbsp; Neither party nor its employees, permitted subcontractors, or agents will, under any circumstances, be considered to be an agent, partner, joint venturer, or representative of the other party, or anything other than an independent contractor for all purposes of this Agreement, and except as may be authorized specifically in writing, neither party has express or implied authority to bind the other in any manner whatsoever by virtue of this Agreement.</li>
                                            <li><strong>Assignment.</strong>&nbsp; This Agreement will be binding upon and inure to the benefit of the parties hereto and their respective successors and permitted assigns and designees; provided, however, neither party will have the right to transfer, assign or delegate its rights or obligations under this Agreement or any portion thereof without the prior written consent of the other party (except that DAWN SCIENTIFIC, INC may assign this Agreement to a parent, subsidiary, or successor corporation without such consent).&nbsp; Notwithstanding the foregoing, DAWN SCIENTIFIC, INC will have the right, without the prior approval of Customer, to appoint subcontractor(s) or agent(s) to perform certain services hereunder.</li>
                                            <li><strong>Mutual Representations.</strong>&nbsp; Each party represents and warrants that it: (i) is authorized to enter into this Agreement and that in so doing it is not in violation of the terms or conditions of any contract or other agreement to which it may be a party; and (ii) has or shall obtain all appropriate consents or permissions to perform its obligations under this Agreement and to disclose any information to the other Party.&nbsp; Customer further represents and warrants that it: (i) shall comply with all applicable laws, rules, and regulations (including, without limitation, permitting and licensing requirements) related to its performance hereunder and in the receipt, handling, storage, possession, transport, disposal, purchase, resale, or use of any Product; and (ii) owns all right, title, and interest in and to, or has full and sufficient right and authority to use in the manner contemplated by this Agreement, any programming, materials, specifications or data furnished by Customer to DAWN SCIENTIFIC, INC in connection with DAWN SCIENTIFIC, INC’s performance of the Services.&nbsp; The Products and Services provided by DAWN SCIENTIFIC, INC are intended for purchase and use by persons or entities acting in a professional, business, or trade capacity (each, a “Commercial Customer”), and are not intended for purchase or use by consumers for personal, family, or household purposes.&nbsp; By ordering Products or Services, Customer represents and warrants that it is a Commercial Customer engaging in a commercial transaction.</li>
                                            <li><strong>Applicable Law.</strong>&nbsp; This Agreement is made pursuant to, and will be construed and enforced exclusively in accordance with, the internal laws of the Commonwealth of Pennsylvania (and U.S. federal law, to the extent applicable) or the principal place of business of the particular DAWN SCIENTIFIC, INC affiliated company transacting business with Customer, without giving effect to otherwise applicable principles of conflicts of law.&nbsp; Any lawsuit arising from or related to this Agreement must be brought exclusively before the U.S. District Court for the Eastern District of Pennsylvania or any Commonwealth court sitting in Delaware County, Pennsylvania, or the applicable courts of the principal place of business of the DAWN SCIENTIFIC, INC affiliated company transacting business with Customer, and each party hereby consents to the jurisdiction of any such court. The parties hereby expressly exclude the application of The United Nations Convention on Contracts for the International Sale of Goods to this Agreement, including, without limitation, Article 35(2) thereof.&nbsp; EACH PARTY HERETO EXPRESSLY AND IRREVOCABLY WAIVES ANY AND ALL RIGHTS TO TRIAL BY JURY IN ANY ACTION, PROCEEDING OR CLAIM RELATING TO OR ARISING IN ANY WAY FROM THIS AGREEMENT, ANY DOCUMENTS EXECUTED IN CONNECTION WITH THIS AGREEMENT, OR ANY TRANSACTION CONTEMPLATED IN ANY SUCH DOCUMENTS.&nbsp; CUSTOMER AND DAWN SCIENTIFIC, INC EACH ACKNOWLEDGE THAT THE FOREGOING WAIVER IS KNOWING AND VOLUNTARY.&nbsp; CUSTOMER EXPRESSLY WAIVES ANY OBJECTION THAT IT MAY HAVE NOW OR LATER TO THE VENUE OR JURISDICTION OF ANY ACTION, INCLUDING, WITHOUT LIMITATION, based upon lack of personal jurisdiction, improper venue, forum non conveniens, or similar grounds.&nbsp; Any action arising under this Agreement, OTHER THAN FOR NON-PAYMENT, must be brought within one (1) year from the date that the cause of action arose.</li>
                                            <li><strong>Merger, Modification, Waiver; Construction and Interpretation; Survival.</strong>&nbsp; This Agreement comprises the entire agreement between the parties with respect to the subject matter hereof, there being no prior or contemporaneous written or oral promises or representations not incorporated herein.&nbsp; No amendment, modification or waiver of the terms of this Agreement will be binding on either party unless reduced to writing and signed by an authorized officer of the party to be bound, and in the case of a waiver, will be effective only in the specific instance and for the specific purpose for which given, and will not be construed as a waiver of any subsequent breach.&nbsp; The failure of either party to enforce at any time or for any period of time any of the provisions of this Agreement will not be construed as a waiver of such provisions or of the right of such party thereafter to enforce each and every such provision.&nbsp; The captions in this Agreement have been inserted for convenience of reference only and do not constitute a part of, and will not be considered in construing, this Agreement.&nbsp; If any portion of this Agreement is held by a court of competent jurisdiction to be invalid for any reason, the remainder of this Agreement will not be deemed invalid but will remain in full force and effect.&nbsp; No course of dealing, usage of trade, or course of performance will supplement, explain, or amend any term, condition, or instruction of this Agreement or any shipment of Products or provision of Services hereunder.&nbsp; Stenographical, clerical, or computer errors on the face of any DAWN SCIENTIFIC, INC quotation, invoice, or other form will be subject to correction by DAWN SCIENTIFIC, INC.&nbsp; Sections 2, 7-9, 11-13, and 15-19 will survive termination of this Agreement or termination or cancellation of any purchase order.&nbsp;</li>
                                            <li><strong>No Third-Party Beneficiary Rights.</strong> &nbsp;This Agreement is not intended to and will not be construed to give any third party any interest or rights (including, without limitation, any third-party beneficiary rights) with respect to or in connection with the subject matter of this Agreement, except as otherwise expressly provided for in this Agreement.</li>
                                            <li><strong>Clearance Sale Terms.</strong>&nbsp; Notwithstanding anything to the contrary herein, the following terms and conditions apply to all clearance sale or clearance priced Products: (i) Products are available in limited quantities on a first come, first serve basis, and pricing is not applicable to substituted items; (ii) additional discounts cannot be combined with clearance sale pricing; (iii) all sales are final, and DAWN SCIENTIFIC, INC will not accept returns for any reason; (iv) sales are limited to the United States; and (v) DAWN SCIENTIFIC, INC reserves the right to modify or terminate the promotion at any time. ALL PRODUCTS ARE PROVIDED “AS IS, WHERE IS” AND WITH ALL FAULTS, AND DAWN SCIENTIFIC, INC MAKES NO WARRANTIES OR GUARANTEES OF ANY KIND WHATSOEVER WITH RESPECT TO THE PRODUCTS, WHETHER STATUTORY, WRITTEN, ORAL, EXPRESS, OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY, NON-INFRINGEMENT, SUITABILITY, SUSTAINABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.</li>
                                        </ol>
                                    </li>
                                </ol>                      
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default Terms;